AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  python3.7

  Sample SAM Template for seenomally-docker-lambda-v1

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 900
    MemorySize: 5000
  Api:
    BinaryMediaTypes:
      - video/mp4
Resources:
  SeenomalyFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      PackageType: Image
      Events:
        Seenomaly:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /Seenomaly
            Method: post

    Metadata:
      Dockerfile: Dockerfile
      DockerContext: .
      DockerTag: python3.7-v1

  # VisualTestVideoBucket:
  #   Type: AWS::S3::Bucket

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  SeenomalyApi:
    Description: "API Gateway endpoint URL for Prod stage for owl eye function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/Seenomaly/"
  SeenomalyFunction:
    Description: "owl eye Lambda Function ARN"
    Value: !GetAtt SeenomalyFunction.Arn
  SeenomalyFunctionIamRole:
    Description: "Implicit IAM Role created for owl eye function"
    Value: !GetAtt SeenomalyFunctionRole.Arn
